
import Image1 from '../../component/assets/images/image1.png';
import Image2 from '../../component/assets/images/image2.png';
import Image3 from '../../component/assets/images/image3.png';
import Image4 from '../../component/assets/images/image4.png';
import Image5 from '../../component/assets/images/image5.png';
import Image6 from '../../component/assets/images/image6.png';
import Image7 from '../../component/assets/images/image1.png';
import Image8 from '../../component/assets/images/image8.png';
import Image9 from '../../component/assets/images/image3.png';
import Image10 from '../../component/assets/images/image4.png';


export const eventsData = [
    {
      id: 1,
      title: 'The Future of Technology',
      date: 'Nov 22',
      venue: 'Online Event',
      price: '₹499',
      interested: 140,
      category: 'Technology',
      imageUrl: Image1, 
      description: 'The Future of Technology is a 2020 online event where participants will learn about the future of technology and how it will impact their lives. The event will feature speakers from Google, Facebook, and other tech companies. Participants will also have the opportunity to network with other tech enthusiasts. The event is free to attend and will take place on November 22, 2020. Register now to secure your spot!'
    },
      {
          id: 2,
          title: 'Webinar on Market Trends',
          date: 'Nov 22',
          venue: 'Online Event',
          price: 'Free',
          interested: 90,
          category: 'Finacial & Market',
          imageUrl: Image2,
          description: 'The open Market is a 2020 online event where participants will learn about the future of technology and how it will impact their lives. The event will feature speakers from Google, Facebook, and other tech companies. Participants will also have the opportunity to network with other tech enthusiasts. The event is free to attend and will take place on November 22, 2020. Register now to secure your spot!',
          restricted: 18,
          restrictedReason: 'Guests only',
          attendees: 190,
          isToday: false,
          isTomorrow: true,
          isThisWeek: false,

          },
          {
              id: 3,
              title: 'Poem and Dance',
              date: 'Nov 22',
              venue: 'Court Yard',
              price: '₹499',
              interested: 10,
              category: 'Art & Culture',
              imageUrl: Image3,
              description: 'Poem and Dance is a 2020 online event where participants will learn about the future of technology and how it will impact their lives. The event will feature speakers from Google, Facebook, and other tech companies. Participants will also have the opportunity to network with other tech enthusiasts. The event is free to attend and will take place on November 22, 2020. Register now to secure your spot!',
              restricted: 18,
              restrictedReason: 18,
              attendees: 100,
              isToday: true,
              isTomorrow: true,
              isThisWeek: false,
              },
              {
                  id: 4,
                  title: 'The Act of God',
                  date: 'Nov 22',
                  venue: 'Toyota Stadium',
                  price: '₹499',
                  interested: 10,
                  category: 'Religion & Spirituality',
                  imageUrl: Image4,
                  isToday: false,
                  isTomorrow: true,
                  isThisWeek: false,
                  },
                  {
                      id: 5,
                      title: 'kings of the world',
                      date: 'April 19',
                      venue: 'Royal Church',
                      price: '#49,900',
                      interested: 10,
                      category: 'Religion & Spirituality',
                      imageUrl: Image5,
                      restricted: true,
                      restrictedReason: 'Guests only',
                      attendees: 100,
                      isToday: false,
                      isTomorrow: true,
                      isThisWeek: true,
                      },
                      {
                          id: 6,
                          title: 'State of the Market',
                          date: 'April 18',
                          venue: 'Online Event',
                          price: '$18:99',
                          interested: 10,
                          category: 'Finacial & Market',
                          imageUrl: Image6,
                          isToday: false,
                          isTomorrow: true,
                          isThisWeek: true,
                          },
                          {
                            id: 7,
                            title: 'Taylor Swift',
                            date: 'Nov 22',
                            venue: 'Online Event',
                            price: '₹499',
                            interested: 10,
                            category: 'Art & Culture',
                            imageUrl: Image7,
                            },
                            {
                                id: 8,
                                title: 'Horse Riding',
                                date: 'Nov 22',
                                venue: 'Online Event',
                                price: 'Free',
                                interested: 10,
                                category: 'Sport & Fitness',
                                imageUrl: Image8,
                                isToday: false,
                                isTomorrow: true,
                                isThisWeek: false,
                                },
                          {
                            id: 9,
                            title: 'The open Market',
                            date: 'Nov 22',
                            venue: 'Online Event',
                            price: '₹499',
                            interested: 10,
                            category: 'Finacial & Market',
                            imageUrl: Image9,
                            },
                            {
                                id: 10,
                                title: 'The open Market',
                                date: 'Nov 22',
                                venue: 'Online Event',
                                price: '₹499',
                                interested: 10,
                                category: 'Finacial & Market',
                                imageUrl: Image10,
                                isToday: true,
                                isTomorrow: true,
                                isThisWeek: false,
                      },
                        
  ];